Allow the configuration of HOY_INVERTER_WATT
reserve85/HoymilesZeroExport pull request #158
Opened 2024-03-04 13:04 UTC by ms49434

HOY_INVERTER_WATT should contain the power rating of the inverter.
HOY_MAX_WATT is used to limit the maximum output of the inverter and can be equal or lower than HOY_INVERTER_WATT.

Example 1:
A Hoymiles inverter HMS-2000-4T has a power rating of 2000 Wp.
The inverter shouldn't produce more than 600 W.

HOY_INVERTER_WATT = 2000
HOY_MAX_WATT = 600

Example 2:
A Hoymiles inverter HM-800-2T has a power rating of 800 Wp.
The maximum power should be the same as the power rating.

HOY_INVERTER_WATT = 800
HOY_MAX_WATT = 800

2024-03-04 13:44 UTC, reserve85 commented
Hello,

looks good, I would never have thought that this could be useful without battery operation, but why not.
Can you please increase the version in the config and script and add a short description in the changelog? Then I can push it into main.

Thank you for your support!

2024-03-04 14:19 UTC, ms49434 commented
Hello,

please double check and let me know if I missed something.

:)

2024-03-05 09:22 UTC, reserve85 requested changes
just add a fallback value so the new entry is just optional.

2024-03-05 11:54 UTC, ms49434 commented on HoymilesZeroExport_Config.ini
> +HOY_INVERTER_WATT = 1500
Modifications have been applied.

2024-03-05 11:57 UTC, reserve85 approved these changes
thank you

2024-03-05 11:57 UTC, merged